//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventiv.Todo.Module.TaskManagement.Localization
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventiv.Todo.Module.TaskManagement.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authentication required..
        /// </summary>
        internal static string ERR_20001
        {
            get
            {
                return ResourceManager.GetString("ERR-20001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value is not in desired format: {0}.
        /// </summary>
        internal static string ERR_20002
        {
            get
            {
                return ResourceManager.GetString("ERR-20002", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Permission denied..
        /// </summary>
        internal static string ERR_20003
        {
            get
            {
                return ResourceManager.GetString("ERR-20003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given credit card number is not valid..
        /// </summary>
        internal static string ERR_20004
        {
            get
            {
                return ResourceManager.GetString("ERR-20004", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given URL is not valid: {0}.
        /// </summary>
        internal static string ERR_20005
        {
            get
            {
                return ResourceManager.GetString("ERR-20005", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record not found with id:{0}.
        /// </summary>
        internal static string ERR_20006
        {
            get
            {
                return ResourceManager.GetString("ERR-20006", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given token is not valid..
        /// </summary>
        internal static string ERR_20007
        {
            get
            {
                return ResourceManager.GetString("ERR-20007", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given card number is not valid..
        /// </summary>
        internal static string ERR_20008
        {
            get
            {
                return ResourceManager.GetString("ERR-20008", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given currency code is not valid: {0}.
        /// </summary>
        internal static string ERR_20009
        {
            get
            {
                return ResourceManager.GetString("ERR-20009", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given date range is not valid: {0}.
        /// </summary>
        internal static string ERR_20010
        {
            get
            {
                return ResourceManager.GetString("ERR-20010", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given date is not valid: {0}.
        /// </summary>
        internal static string ERR_20011
        {
            get
            {
                return ResourceManager.GetString("ERR-20011", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given email is not valid: {0}.
        /// </summary>
        internal static string ERR_20012
        {
            get
            {
                return ResourceManager.GetString("ERR-20012", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given money range is not valid: {0}.
        /// </summary>
        internal static string ERR_20013
        {
            get
            {
                return ResourceManager.GetString("ERR-20013", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given money is not valid: {0}.
        /// </summary>
        internal static string ERR_20014
        {
            get
            {
                return ResourceManager.GetString("ERR-20014", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given identity number is not valid: {0}.
        /// </summary>
        internal static string ERR_20015
        {
            get
            {
                return ResourceManager.GetString("ERR-20015", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given time range is not valid: {0}.
        /// </summary>
        internal static string ERR_20016
        {
            get
            {
                return ResourceManager.GetString("ERR-20016", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given time is not valid: {0}.
        /// </summary>
        internal static string ERR_20017
        {
            get
            {
                return ResourceManager.GetString("ERR-20017", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given tax number is not valid: {0}.
        /// </summary>
        internal static string ERR_20018
        {
            get
            {
                return ResourceManager.GetString("ERR-20018", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given value is not in supported values: {0}.
        /// </summary>
        internal static string ERR_20019
        {
            get
            {
                return ResourceManager.GetString("ERR-20019", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start date should be before end date: {0}.
        /// </summary>
        internal static string ERR_20020
        {
            get
            {
                return ResourceManager.GetString("ERR-20020", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start amount should be less than end amount: {0}.
        /// </summary>
        internal static string ERR_20021
        {
            get
            {
                return ResourceManager.GetString("ERR-20021", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start time should be before end time: {0}.
        /// </summary>
        internal static string ERR_20022
        {
            get
            {
                return ResourceManager.GetString("ERR-20022", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given value should be &apos;True&apos;, &apos;False&apos; or &apos;Undefined&apos;.
        /// </summary>
        internal static string ERR_20023
        {
            get
            {
                return ResourceManager.GetString("ERR-20023", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currency not supported: {0}.
        /// </summary>
        internal static string ERR_20024
        {
            get
            {
                return ResourceManager.GetString("ERR-20024", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given rate is not valid: {0}.
        /// </summary>
        internal static string ERR_20025
        {
            get
            {
                return ResourceManager.GetString("ERR-20025", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given timestamp is not valid: {0}.
        /// </summary>
        internal static string ERR_20026
        {
            get
            {
                return ResourceManager.GetString("ERR-20026", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given date time is not valid: {0}.
        /// </summary>
        internal static string ERR_20027
        {
            get
            {
                return ResourceManager.GetString("ERR-20027", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given date time range is not valid: {0}.
        /// </summary>
        internal static string ERR_20028
        {
            get
            {
                return ResourceManager.GetString("ERR-20028", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start date time should be before end date time: {0}.
        /// </summary>
        internal static string ERR_20029
        {
            get
            {
                return ResourceManager.GetString("ERR-20029", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given guid is not valid: {0}.
        /// </summary>
        internal static string ERR_20030
        {
            get
            {
                return ResourceManager.GetString("ERR-20030", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Request ID is required for this operation..
        /// </summary>
        internal static string ERR_20031
        {
            get
            {
                return ResourceManager.GetString("ERR-20031", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given binary value is not in base64 format..
        /// </summary>
        internal static string ERR_20032
        {
            get
            {
                return ResourceManager.GetString("ERR-20032", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum daily request count exceeded..
        /// </summary>
        internal static string ERR_20033
        {
            get
            {
                return ResourceManager.GetString("ERR-20033", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given IBAN is not valid: {0}.
        /// </summary>
        internal static string ERR_20034
        {
            get
            {
                return ResourceManager.GetString("ERR-20034", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given geolocation is not valid: {0}.
        /// </summary>
        internal static string ERR_20035
        {
            get
            {
                return ResourceManager.GetString("ERR-20035", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given time span is not valid: {0}.
        /// </summary>
        internal static string ERR_20036
        {
            get
            {
                return ResourceManager.GetString("ERR-20036", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given tax or identity number is not valid: {0}.
        /// </summary>
        internal static string ERR_20037
        {
            get
            {
                return ResourceManager.GetString("ERR-20037", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given mime type is not valid: {0}.
        /// </summary>
        internal static string ERR_20038
        {
            get
            {
                return ResourceManager.GetString("ERR-20038", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given country code is not valid: {0}.
        /// </summary>
        internal static string ERR_20039
        {
            get
            {
                return ResourceManager.GetString("ERR-20039", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This operation is not yet implemented..
        /// </summary>
        internal static string ERR_20040
        {
            get
            {
                return ResourceManager.GetString("ERR-20040", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given password is not valid..
        /// </summary>
        internal static string ERR_20041
        {
            get
            {
                return ResourceManager.GetString("ERR-20041", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Given encrypted text is not valid..
        /// </summary>
        internal static string ERR_20042
        {
            get
            {
                return ResourceManager.GetString("ERR-20042", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Snapshot isolation transaction aborted due to update conflict..
        /// </summary>
        internal static string ERR_20101
        {
            get
            {
                return ResourceManager.GetString("ERR-20101", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; is already added to board &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_20701
        {
            get
            {
                return ResourceManager.GetString("ERR-20701", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; is not added to board &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_20702
        {
            get
            {
                return ResourceManager.GetString("ERR-20702", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This column &apos;{0}&apos; does not belong to this board &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_20703
        {
            get
            {
                return ResourceManager.GetString("ERR-20703", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is required for this operation..
        /// </summary>
        internal static string ERR_20704
        {
            get
            {
                return ResourceManager.GetString("ERR-20704", resourceCulture);
            }
        }
    }
}
